### ISSUE TITLE
^ is rejected

### ISSUE THREAD

**Issue by pterjan** [ingydotnet/yaml-pm#136]
Starting a non quoted string with ^ gets it rejected with YAML_PARSE_ERR_BAD_IMPLICIT.

YAML spec says:

```
The “@” and “`” are reserved for future use.
```

but the Loader rejects:

```
/^[\@\`\^]/.
```

I noticed this as this prevents loading META.yml from Moose as https://github.com/moose/Moose/blob/master/dist.ini#L164 gets included unquoted as:

```
    - ^Class::MOP::Attribute$
```

**Comment by perlpunk** [comment]
I believe this has been fixed in version 1.12
see also https://rt.cpan.org/Ticket/Display.html?id=97870

please reopen if necessary
