### ISSUE TITLE
clang built perl will hang in test

### ISSUE THREAD

**Issue by Tux** [ingydotnet/yaml-pm#141]
$ perl -V
Summary of my perl5 (revision 5 version 21 subversion 5) configuration:

  Platform:
    osname=linux, osvers=3.11.10-21-desktop, archname=i686-linux-64int-ld
    uname='linux lx09 3.11.10-21-desktop #1 smp preempt mon jul 21 15:28:46 utc 2014 (9a9565d) i686 i686 i386 gnulinux '
    config_args='-Dusedevel -Dcc=clang -Accflags=-fsanitize=address -Aldflags=-fsanitize=address -Alddlflags='-shared -fsanitize=address' -Duse64bitint -Duselongdouble -des -Dusedevel -Uinstallusrbinperl -Dprefix=/media/Tux/perls-c'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=undef, uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='clang', ccflags ='-fsanitize=address -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2',
    optimize='-O2',
    cppflags='-fsanitize=address -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 Compatible Clang 3.3 (branches/release_33 183898)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12, longdblkind=3
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='clang', ldflags =' -fsanitize=address -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/bin/../lib/clang/3.3/lib /usr/lib /lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.18.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.18'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags=' -shared -fsanitize=address -L/usr/local/lib -fstack-protector'

Characteristics of this binary (from libperl):
  Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
                        PERL_NEW_COPY_ON_WRITE PERL_PRESERVE_IVUV
                        PERL_USE_DEVEL USE_64_BIT_INT USE_LARGE_FILES
                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_LOCALE_TIME USE_LONG_DOUBLE
                        USE_PERLIO USE_PERL_ATOF
  Built under linux
  Compiled at Oct 20 2014 18:22:05
  @INC:
    /media/Tux/perls-c/lib/site_perl/5.21.5/i686-linux-64int-ld
    /media/Tux/perls-c/lib/site_perl/5.21.5
    /media/Tux/perls-c/lib/5.21.5/i686-linux-64int-ld
    /media/Tux/perls-c/lib/5.21.5
    /media/Tux/perls-c/lib/site_perl
    .

Reproduce build with something like

$ ./Configure -Dcc=clang -Accflags=-fsanitize=address -Aldflags=-fsanitize=address -Alddlflags='-shared -fsanitize=address' -Dusedevel -des

$ make test will hang here:

PERL_DL_NONLAZY=1 /media/Tux/perls-c/bin/perl5.21.5 "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
t/000-compile-modules.t .. ok
t/2-scalars.t ............ 1/?

Running it by hand

$ cperl5.21.5 -Iblib/lib -Iblib/arch t/2-scalars.t
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
<hang>

**Comment by aggrolite** [comment]
I've run into this same issue, but on DragonFly BSD. However, my Perl install is built with GCC 4.7

**Comment by bingos** [comment]
Seeing it now on Dragonfly BSD v4.0.6-RELEASE x64

USER     PID %CPU %MEM    VSZ    RSS TT  STAT   STARTED      TIME COMMAND
cpan  761077 95.8  9.2 105416  80304  0  RQ0L+   8:04AM   1:18.07 /usr/home/cpan/pit/thr/perl-5.18.4/bin/perl5.18.4 t/2-scalars.t

Compiler is gcc version 4.7.4 [DragonFly] Release/2014-06-12

Seems to be consistent for all the 54 perls on this CPAN smoker.

**Comment by perlpunk** [comment]
This sounds like the same problem as with the perl compiled with libasan, see #186.

Should be fixed in YAML 1.24_001, coud you test it again?

**Comment by perlpunk** [comment]
Please reopen if the issue still exists
