### ISSUE TITLE
Empty value are loaded as undef

### ISSUE THREAD

**Issue by crazytan** [ingydotnet/yaml-pm#178]
I'm using the library to load a simple document with a single key and empty value:
```yaml
key: 
```
In the loaded hash, `key` is mapped to `undef`. I understand this is a reasonable choice (value could be any data structure), but an empty string may be a better default here? It enables application code to handle corner cases more gracefully.

**Comment by crazytan** [comment]
BTW, I see that on CPAN page that the module will be changed to an interface for faster libraries written in C. But it seems a shame to me that there is no satisfying YAML parser written in pure Perl right now, considering Perl has excellent text processing capability. Pure perl is still useful in some places where we may want to distribute our scripts to environments without internet access and it could be a pain to bundle C-based CPAN modules. So, what's the development plan for this module? I'm happy to contribute and make it more complete.

**Comment by perlpunk** [comment]
The spec (for 1.2) at least suggests that empty values are resolved as null: http://yaml.org/spec/1.2/spec.html#id2786563

And in fact is the most common way for most frameworks I have checked - the ones we support currently in the https://github.com/yaml/yaml-editor

I could imagine making this configurable in a new YAML loader...

**Comment by perlpunk** [comment]
@crazytan we are actually working on various YAML things, including a new parser.
See:
https://github.com/yaml/yaml-editor
https://github.com/yaml/yaml-test-suite
https://github.com/perlpunk/yaml-test-matrix
http://matrix.yaml.io/
https://github.com/perlpunk/YAML-PP-p5
The code in YAML.pm itself is supposed to be only in YAML::Old, which the new YAML.pm delegating to it.

**Comment by crazytan** [comment]
Thanks for the quick reply! If it's part of the spec then I agree this should be a default behavior. And making this configurable would be nice. I'm excited that you guys are working on a new parser.
