### ISSUE TITLE
bugged, unusable: DumpFile for an array of hash , LoadFile this and you will have an HARRY instead

### ISSUE THREAD

**Issue by jerome-diver** [ingydotnet/yaml-pm#179]
Why when i DumpFile an ARRAY of HASHES (then read inside the file the content well made), after when i LoadFile from this file, i have a HASH instead of ARRAY ?
that make this module unusable.
or maybe i not undersatnd something, please explain me.

**Comment by perlpunk** [comment]
Can you please post some code?

like so:
```
use Data::Dumper;
use YAML qw/ LoadFile DumpFile /;
my @array_of_hashes = ( { id => 1 }, { id => 2 } );
DumpFile("/tmp/foo.yaml", \@array_of_hashes);
my $loaded = LoadFile("/tmp/foo.yaml");
say Dumper $loaded;
___END___
$VAR1 = [
          {
            'id' => '1'
          },
          {
            'id' => '2'
          }
        ];
```
So, as you can see, it works.

Please show some code first next time. Thank you.

**Comment by perlpunk** [comment]
Closing because no feedback.
