### ISSUE TITLE
YAML Dumper correctly writes database but YAML Loader omits multiple whitespaces.

### ISSUE THREAD

**Issue by wilyarti** [ingydotnet/yaml-pm#183]
I have a YAML database with multiple hash entries. Some of these have multiple spaces in the filenames.

When the database is written the filename is correct. However when using YAML::Loader it will remove the occurrence of whitespace. If there are 4 spaces in a row it will be replaced with one space.

I have a sample database and perl script that replicates this error.

This may or not be a bug. If it isn't how to I get it to leave the white spaces in?

Here is a same database and perl script:
[TEST.pl.txt](https://github.com/ingydotnet/yaml-pm/files/1502977/TEST.pl.txt)
[TEST.yaml.txt](https://github.com/ingydotnet/yaml-pm/files/1502978/TEST.yaml.txt)

**Comment by perlpunk** [comment]
Yes, this is a known bug and only happens, if the scalar is on the `---` line.
There is a PR #172 for that

**Comment by wilyarti** [comment]
Thanks! That worked.
