### ISSUE TITLE
YAML::Any: No way to prefer a specific backend

### ISSUE THREAD

**Issue by karenetheridge** [ingydotnet/yaml-pm#20]
There is no way to say "prefer to use YAML::Syck over YAML::XS", etc.  JSON::Any uses an environment variable to specify which backends are acceptable, and the order in which they can be applied.

**Comment by perlpunk** [comment]
It can be done with setting `@YAML::Any::_TEST_ORDER`:

    @YAML::Any::_TEST_ORDER = qw/ YAML::XS YAML::Syck /;
