### ISSUE TITLE
1.25 breaks Rex, possible regression

### ISSUE THREAD

**Issue by gregoa** [ingydotnet/yaml-pm#208]
https://bugs.debian.org/898578 looks like a possible regression in yaml-pm breaking at least Rex.
@ntyni has bisected it to a specific commit already.

Thanks in advance for checking,
gregor herrmann, Debian Perl Group

**Comment by perlpunk** [comment]
thanks! I think I fixed it, will upload a new version as soon as possible

**Comment by perlpunk** [comment]
Released 1.25_002

**Comment by perlpunk** [comment]
Released 1.26, thanks again!
