### ISSUE TITLE
QuoteNumericStrings = 1 have no effect when i use '1_1' as hash key

### ISSUE THREAD

**Issue by rth1969** [ingydotnet/yaml-pm#216]
When i like to write a perl hash into a yaml i didn't get  quotes when i set QuoteNumericStrings=1, this is an issue when i read the yaml back because 11 will be overruled by 1_1.

```
use Data::Dumper;  
use YAML;
local $YAML::QuoteNumericStrings = 1;

my %hash = (
           '11'  => { 'TEST' => 'my_test_1' },
           '1_1' => { 'TEST' => 'my_test_2' }
           );

print Dumper \%hash;

YAML::DumpFile( "my.yaml",\%hash );
```
result in 
```
---
11:
  TEST: my_test_1
1_1:
  TEST: my_test_2
```
and not in 
```
---
'11':
  TEST: my_test_1
'1_1':
  TEST: my_test_2
```

edit @perlpunk Add code markers

**Comment by perlpunk** [comment]
Which YAML.pm version are you using?
```
% perl -wE'
use YAML;
local $YAML::QuoteNumericStrings = 1;
my %hash = ( "11" => "a", "1_1" => "b" );
use Data::Dumper;
my $yaml = Dump(\%hash);
say $yaml;
my $d = Load($yaml);
say Dumper $d;'
Name "YAML::QuoteNumericStrings" used only once: possible typo at -e line 3.
---
'11': a
1_1: b

$VAR1 = {
          '1_1' => 'b',
          '11' => 'a'
        };
```

**Comment by perlpunk** [comment]
Note: The warning about the variable appears because apparently it was never added to the list of global vars. I will add that.

**Comment by perlpunk** [comment]
I would really need some more information from you.
So far I can only say that this feature was added in 1.14, and it works like expected for me.
A string like `1_1` won't be quoted though because it won't be seen as a number.

I'm closing this. Please reopen if you can provide a use case that shows the problem.
