### ISSUE TITLE
YAML.pm takes forever with embedded ^M

### ISSUE THREAD

**Issue by eserte** [ingydotnet/yaml-pm#29]
A YAML document with an embedded ASCII 13, e.g. (please replace ^M with the control char)

```

---
abstract: "Perl interface to Firmata for the arduino platform.^M"
```

causes an endless loop with the oneliner

```
perl5.18.2 -MYAML=LoadFile -e 'LoadFile(shift)' ascii13.yml
```

I see this behavior with YAML 0.95, but not with YAML 0.81.

**Comment by perlpunk** [comment]
Closing this as #135 is about the same issue and has comments.
Also a current YAML.pm doesn't hang anymore, but dies with a parsing error.
