### ISSUE TITLE
Problems installing YAML

### ISSUE THREAD

**Issue by darmstro** [ingydotnet/yaml-pm#34]
I'm trying to reinstall YAML on CentOS, but build.log says "CPAN::Meta::YAML 0.011 is not available at /usr/lib/perl5/5.8.8/CPAN/Meta.pm line 320".  I get same thing installing any of the dependent modules  (Spiffy, Test::YAML, Exporter).
I downloaded YAML-1.01.tar.gz and got same error running Makefile.PL

I had them installed OK last week but our application constantly complained "Can't locate method 'new' via package "YAML" at /usr/lib/perl5/site_per/5.8.8/YAML.pm line 24" and I couldn't find a YAML 'new' method anywhere.  I was hoping reinstalling may help, but now it won't install.  
Thanks.
PS. I'm Perl & CPAN newbie.

**Comment by perlpunk** [comment]
This is probably because on CentOS, many core modules shipped with perl are not included in the CentOS perl package - you need to install the `perl-core` package.
